project:
  type: website
  output-dir: docs

website:
  title: "QUB-PsyR"
  navbar:
    logo: images/QUBlogoWsmall.png
    right:
      - text: "Intro"
        menu:
        - text: "R and RStudio"
          href: intro1.html
        - text: "Running Code in R"
          href: intro2.html
        - text: "Objects and Functions"
          href: intro3.html
        - text: "Data Frames and Lists"
          href: intro4.html
        - text: "Saving and Loading Data"
          href: intro5.html
      - text: "Working with R Objects"
        menu:
        - text: "Binary Operators"
          href: working1.html
        - text: "Functions"
          href: working2.html
        - text: "Numerical Indexing"
          href: working3.html
        - text: "Logical Indexing"
          href: working4.html
        - text: "R Packages"
          href: working5.html
      - text: "Statistical Inference"
        menu:
        - text: "A Primer on Statistical Inference"
          href: inference0.html
        - text: "The t-test"
          href: inference1.html
        - text: "The Chi²-test"
          href: inference2.html
        - text: "Correlations"
          href: inference3.html
        - text: "One-factorial Analysis of Variance"
          href: inference4.html
        - text: "Two-factorial Analysis of Variance"
          href: inference5.html
        - text: "Repeated measures and mixed ANOVAs"
          href: inference6.html
        - text: "Simple linear regression"
          href: inference7.html
        - text: "Multiple linear regression"
          href: inference8.html
        - text: "Multi-level models"
          href: inference9.html
        
      - text: "About"
        href: about.html


format:
  html:
    theme: 
      - cerulean
      - custom.scss

  

